
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include <react/renderer/components/rnx-gradient/Props.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook {
namespace react {

LinearGradientViewProps::LinearGradientViewProps(
    const LinearGradientViewProps &sourceProps,
    const RawProps &rawProps): ViewProps(sourceProps, rawProps),

    start(convertRawProp(rawProps, "startPoint", sourceProps.start, {})),
    end(convertRawProp(rawProps, "endPoint", sourceProps.end, {})),
    colors(convertRawProp(rawProps, "colors", sourceProps.colors, {})),
    locations(convertRawProp(rawProps, "locations", sourceProps.locations, {})),
    useAngle(convertRawProp(rawProps, "useAngle", sourceProps.useAngle, {false})),
    angleCenter(convertRawProp(rawProps, "angleCenter", sourceProps.angleCenter, {})),
    angle(convertRawProp(rawProps, "angle", sourceProps.angle, {0.0})) { }

} // namespace react
} // namespace facebook
